[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sdf"
dynamic = ["version"]
description = "Python module for processing SDF files"
dependencies = [
  "numpy",
]
authors = [
     {name = "Keith Bennett", email = "k.bennett@warwick.ac.uk"},
]
